source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DiamondSwitch_Example', :exclusive => true do
  pod "DiamondSwitch", :path => "../"
end

target 'DiamondSwitch_Tests', :exclusive => true do
  pod "DiamondSwitch", :path => "../"

  
end
